#!/usr/bin/python
# Used to automatically pull in external dependencies defined in Maven into Pants' 3rdparty BUILD

import logging
import os
import sys
from textwrap import dedent

from pom_utils import PomUtils


logger = logging.getLogger(__name__)


class ExternalProtosBuildGenerator(object):

  def __init__(self):
    pass

  def generate(self):
    handler = PomUtils.external_protos_content_handler()
    return dedent("""\
      # Automatically generated by {script}
      jar_library(
        name='latest-all-protos',
        jars=[
          # This version is used the majority of BUILD files in external-protos as the latest version of all-protos to extract .proto sources from
          # Seeded from the external-protos.all-protos-latest property defined in external/protos/pom.xml
          jar(org='com.squareup.protos', name='all-protos', rev='{rev}'),
        ],
      )
      """.format(script=os.path.basename(sys.argv[0]),
                      rev=handler.properties['external-protos.all-protos-latest']))

def main():
  """Test driver that spits out parents/external-protos/BUILD.gen contents.
     Run from ~/Development/java
  """
  print(ExternalProtosBuildGenerator().generate())


if __name__ == "__main__":
  PomUtils.parse_common_args(sys.argv[1:])
  main()
