#!/usr/bin/python
# Used to automatically pull in external dependencies defined in Maven into Pants' 3rdparty BUILD

import logging
import os
import sys
from textwrap import dedent

from pom_file import PomFile
from pom_utils import PomUtils
from target_template import Target


logger = logging.getLogger(__name__)


class ExternalProtosBuildGenerator(object):

  def __init__(self):
    pass

  def generate(self):
    handler = PomUtils.external_protos_content_handler()
    pom_file = PomFile('parents/external-protos/pom.xml')
    jar_dep = Target.jar.format(org='com.squareup.protos',
                                name='all-protos',
                                rev=handler.properties['external-protos.all-protos-latest'],
                                symbols=pom_file.properties,
                                file_name=pom_file.path)
    template = dedent("""\
          # Automatically generated by {script}
          # The jar version is used the majority of BUILD files in external-protos as the latest version of all-protos to extract .proto sources from
          # Seeded from the external-protos.all-protos-latest property defined in external/protos/pom.xml
          {target}

          target(name='test')
          """)
    return template.format(script=os.path.basename(sys.argv[0]),
                           target=Target.jar_library.format(name='latest-all-protos',
                                                            jars=[jar_dep],))

def main():
  """Test driver that spits out parents/external-protos/BUILD.gen contents.
     Run from ~/Development/java
  """
  print(ExternalProtosBuildGenerator().generate())


if __name__ == "__main__":
  PomUtils.parse_common_args(sys.argv[1:])
  main()
