# squarepants/src/main/python/squarepants/plugins/BUILD
# HANDWRITTEN


target(name='plugins',
  dependencies = [
    'squarepants/src/main/python/squarepants/plugins/copy_signed_jars',
    'squarepants/src/main/python/squarepants/plugins/jar_manifest',
    'squarepants/src/main/python/squarepants/plugins/jax_ws',
    'squarepants/src/main/python/squarepants/plugins/link_resources_jars',
    'squarepants/src/main/python/squarepants/plugins/repo',
    'squarepants/src/main/python/squarepants/plugins/ruby',
    'squarepants/src/main/python/squarepants/plugins/sake_wire_codegen',
    'squarepants/src/main/python/squarepants/plugins/sjar',
    'squarepants/src/main/python/squarepants/plugins/square_depmap',
    'squarepants/src/main/python/squarepants/plugins/square_idea',
    'squarepants/src/main/python/squarepants/plugins/square_manifest',
    'squarepants/src/main/python/squarepants/plugins/staging_build',
  ],
)
